name: Test and deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies (except pywin32 on non-Windows)
      run: |
        python -m pip install --upgrade pip
        grep -v 'pywin32' requirements.txt | pip install -r /dev/stdin

    - name: Lint with flake8
      run: |
        flake8 .

    - name: Run tests with pytest
      run: |
        pytest